feat: add gap, gapColumn & gapRow styles (Issue #74)
OsmiCSX/osmicsx pull request #84
Opened 2024-03-01 08:36 UTC by JadlionHD

#74

2024-03-01 08:48 UTC, DeVoresyah requested changes
please also provide new custom theme key for gap

2024-03-01 08:52 UTC, DeVoresyah commented
## Example
### Custom Theme
```
{
  "gap": {
     97: 388
   }
}
```

### Output Avaibility
- gap-97
- gap-x-97
- gap-y-97

2024-03-01 15:01 UTC, JadlionHD commented
Thanks for the feedback, here's testing development react native web for custom theme gaps
![image](https://github.com/OsmiCSX/osmicsx/assets/48410066/9cf27667-2398-4f40-819a-d2238f96ba82)

2024-03-01 18:05 UTC, DeVoresyah requested changes
minor changes needed

2024-03-01 18:05 UTC, DeVoresyah commented on src/processor/gaps.ts
please use `.reduce` to make it more simple and clean. You can refer to `letterSpacings.ts`

2024-03-02 01:15 UTC, JadlionHD commented on src/processor/gaps.ts
Sure, done

2024-03-02 16:14 UTC, DeVoresyah approved these changes
LGTM~!

2024-03-02 16:14 UTC, merged